# Generated by Django 2.1.5 on 2022-04-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="arquivo",
            field=models.FileField(default="", upload_to="documentos"),
            preserve_default=False,
        ),
    ]
