# Generated by Django 2.0 on 2022-04-06 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_pertencente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='pertencente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.Funcionario'),
            preserve_default=False,
        ),
    ]
