# Generated by Django 2.1.5 on 2022-04-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registro_hora_extra", "0002_registrohoraextra_horas"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrohoraextra",
            name="utilizada",
            field=models.BooleanField(default=False),
        ),
    ]
